server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-v2
    username: postgres
    password: Gold#3366
  rabbitmq:
    addresses: amqps://fwivvzvm:OTO_tgdrr0wY0YXUQvY9-bZLBSekc2js@crow.rmq.cloudamqp.com/fwivvzvm  
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc: 
        lob.non-contextual-creation:true
    properties:
      hibernate:
        show-sql: true

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser/'
  broker:
    exchange:
      userEventExchange: ead.userevent
    queue:
      userEventQueue:
        name: ead.userevent.ms.course
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost      
