server:
  port: 8082
  servlet:
    context-path: '/ead-course/'
spring:
  application:
    name: ead-course-service
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: Gold#3366
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc: 
        lob.non-contextual-creation:true
    properties:
      hibernate:
        show-sql: true

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service'
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka'
  instance:
    hostname: localhost      
